services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/DockerfileLocal
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./:/app/
      - ./public_html:/app/ # application
      # - /etc/letsencrypt:/etc/letsencrypt:ro # SSL CERTBOT
      - ./docker/nginx/nginx.angular.conf:/etc/nginx/conf.d/default.conf # ap√≥s gerar o certificado passar essa conf
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/DockerfileLocal
    restart: always
    volumes:
      # - ./:/app/
      - ./public_html:/app/
